#  Copyright 2023 Stanford University Convex Optimization Group
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
name: Convert Marimo to HTML
description: "Converts Marimo .py files to HTML format for documentation"

inputs:
  source_folder:
    description: 'Source directory containing Marimo .py files'
    required: false
    default: 'book/marimo'
  working-directory:
    description: 'Directory where the Python project is located'
    required: false
    default: '.'
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'

runs:
  using: composite
  steps:
    # This is not using any github-token:
    - name: Install uv
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh

        # Add UV to PATH for the current shell session
        echo "$HOME/.local/bin" >> $GITHUB_PATH   # Add UV binary directory to PATH in GitHub Actions environment
        export PATH="$HOME/.local/bin:$PATH"      # Add UV binary directory to PATH for the current shell session

        # "Verify UV installation"
        uv --version  # Should print the installed version of UV

    - name: Set up Python environment with uv
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # Create venv
        uv venv --python ${{ inputs.python-version }}
        # Add venv to PATH
        echo ".venv/bin" >> $GITHUB_PATH
        uv sync --all-extras --dev --frozen

    - name: Install marimo
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        uv pip install --no-cache-dir marimo

    - name: Create output directory
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        mkdir -p artifacts/marimo

    - name: Convert Marimo files to HTML
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ ! -d "${{ inputs.source_folder }}" ]; then
          echo "Error: Source directory ${{ inputs.source_folder }} does not exist"
          exit 1
        fi

        found_files=0
        for file in "${{ inputs.source_folder }}"/*.py; do
          if [ -f "$file" ]; then
            found_files=1
            filename=$(basename "$file" .py)
            echo "Converting $filename.py to HTML..."
            uv run marimo export html "$file" -o "artifacts/marimo/${filename}.html"
          fi
        done

        if [ "$found_files" -eq 0 ]; then
          echo "Warning: No .py files found in ${{ inputs.source_folder }}"
          exit 0
        fi

    - name: Upload HTML artifacts
      if: ${{ env.ACT != 'true' }}  # Skip if running with 'act'
      uses: actions/upload-artifact@v4
      with:
        name: marimo
        path: ${{ inputs.working-directory }}/artifacts/marimo
        retention-days: 1
