name: Build LaTeX document

on:
  push

jobs:
  build_paper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: cvxgrp/.github/actions/latex@main
        with:
          paper: XXX.tex
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
