name: Makefile CI

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run clean
      run: make clean

    - name: Run help
      run: make help
